# Generated by Django 3.2 on 2021-04-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_answer_qid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='qid',
            new_name='post',
        ),
    ]
